/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "exercises" CASCADE;

CREATE TABLE "exercises" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "intensity_level" SMALLINT NOT NULL,
  "difficulty_level" SMALLINT NOT NULL,
  "primary_muscle" BIGINT NOT NULL,
  "secondary_muscle" BIGINT NULL,
  "equipment" BIGINT NULL);

ALTER TABLE "exercises"
  ADD CONSTRAINT "primary_muscle_fk"
    FOREIGN KEY ("primary_muscle")
    REFERENCES "muscles" ("id")
    INITIALLY DEFERRED,
  ADD CONSTRAINT "secondary_muscle_fk"
    FOREIGN KEY ("secondary_muscle")
    REFERENCES "muscles" ("id")
    INITIALLY DEFERRED,
  ADD CONSTRAINT "equipment_fk"
    FOREIGN KEY ("equipment")
    REFERENCES "equipment" ("id")
    INITIALLY DEFERRED;

