/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "training_plans" CASCADE;

CREATE TABLE "training_plans" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "duration_minutes" BIGINT NOT NULL,
  "difficulty_level" SMALLINT NOT NULL,
  "created_at" TIMESTAMP NULL,
  "is_public" BOOLEAN NOT NULL,
  "user" BIGINT NOT NULL);

ALTER TABLE "training_plans"
  ADD CONSTRAINT "user_fk"
    FOREIGN KEY ("user")
    REFERENCES "users" ("id")
    INITIALLY DEFERRED;

