/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "training_plan_exercises" CASCADE;

CREATE TABLE "training_plan_exercises" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "order" SMALLINT NOT NULL,
  "notes" TEXT NOT NULL,
  "training_plan" BIGINT NOT NULL,
  "exercise" BIGINT NOT NULL);

ALTER TABLE "training_plan_exercises"
  ADD CONSTRAINT "training_plan_fk"
    FOREIGN KEY ("training_plan")
    REFERENCES "training_plans" ("id")
    INITIALLY DEFERRED,
  ADD CONSTRAINT "exercise_fk"
    FOREIGN KEY ("exercise")
    REFERENCES "exercises" ("id")
    INITIALLY DEFERRED;

