/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "planned_sets" CASCADE;

CREATE TABLE "planned_sets" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "trainingPlanExercise" BIGINT NOT NULL,
  "set_number" BIGINT NOT NULL,
  "target_repetitions" BIGINT NOT NULL,
  "target_weight_kg" DOUBLE PRECISION NOT NULL,
  "target_rest_seconds" BIGINT NOT NULL,
  "notes" TEXT NOT NULL);

ALTER TABLE "planned_sets"
  ADD CONSTRAINT "trainingPlanExercise_fk"
    FOREIGN KEY ("trainingPlanExercise")
    REFERENCES "training_plan_exercises" ("id")
    INITIALLY DEFERRED;

