/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "workout_sessions" CASCADE;

CREATE TABLE "workout_sessions" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "description" TEXT NOT NULL,
  "started_at" TIMESTAMP NULL,
  "ended_at" TIMESTAMP NULL,
  "status" SMALLINT NOT NULL,
  "user" BIGINT NOT NULL,
  "training_plan" BIGINT NULL);

ALTER TABLE "workout_sessions"
  ADD CONSTRAINT "user_fk"
    FOREIGN KEY ("user")
    REFERENCES "users" ("id")
    INITIALLY DEFERRED,
  ADD CONSTRAINT "training_plan_fk"
    FOREIGN KEY ("training_plan")
    REFERENCES "training_plans" ("id")
    INITIALLY DEFERRED;

