/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "workout_session_exercises" CASCADE;

CREATE TABLE "workout_session_exercises" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "order" SMALLINT NOT NULL,
  "notes" TEXT NOT NULL,
  "workout_session" BIGINT NOT NULL,
  "exercise" BIGINT NOT NULL);

ALTER TABLE "workout_session_exercises"
  ADD CONSTRAINT "workout_session_fk"
    FOREIGN KEY ("workout_session")
    REFERENCES "workout_sessions" ("id")
    INITIALLY DEFERRED,
  ADD CONSTRAINT "exercise_fk"
    FOREIGN KEY ("exercise")
    REFERENCES "exercises" ("id")
    INITIALLY DEFERRED;

