/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "performed_sets" CASCADE;

CREATE TABLE "performed_sets" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "workoutSessionExercise" BIGINT NOT NULL,
  "plannedSet" BIGINT NULL,
  "set_number" BIGINT NOT NULL,
  "repetitions" BIGINT NOT NULL,
  "weight_kg" DOUBLE PRECISION NOT NULL,
  "rest_seconds" BIGINT NOT NULL,
  "completed" BOOLEAN NOT NULL,
  "notes" TEXT NOT NULL);

ALTER TABLE "performed_sets"
  ADD CONSTRAINT "workoutSessionExercise_fk"
    FOREIGN KEY ("workoutSessionExercise")
    REFERENCES "workout_session_exercises" ("id")
    INITIALLY DEFERRED,
  ADD CONSTRAINT "plannedSet_fk"
    FOREIGN KEY ("plannedSet")
    REFERENCES "planned_sets" ("id")
    INITIALLY DEFERRED;

