/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "body_measurements" CASCADE;

CREATE TABLE "body_measurements" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "measured_at" TIMESTAMP NULL,
  "weight_kg" DOUBLE PRECISION NOT NULL,
  "body_fat_percentage" DOUBLE PRECISION NOT NULL,
  "chest_cm" SMALLINT NOT NULL,
  "waist_cm" SMALLINT NOT NULL,
  "arm_cm" SMALLINT NOT NULL,
  "leg_cm" SMALLINT NOT NULL,
  "user" BIGINT NOT NULL);

ALTER TABLE "body_measurements"
  ADD CONSTRAINT "user_fk"
    FOREIGN KEY ("user")
    REFERENCES "users" ("id")
    INITIALLY DEFERRED;

