/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "personal_records" CASCADE;

CREATE TABLE "personal_records" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "weight_kg" DOUBLE PRECISION NOT NULL,
  "repetitions" SMALLINT NOT NULL,
  "achieved_at" TIMESTAMP NULL,
  "user" BIGINT NOT NULL,
  "exercise" BIGINT NOT NULL);

ALTER TABLE "personal_records"
  ADD CONSTRAINT "user_fk"
    FOREIGN KEY ("user")
    REFERENCES "users" ("id")
    INITIALLY DEFERRED,
  ADD CONSTRAINT "exercise_fk"
    FOREIGN KEY ("exercise")
    REFERENCES "exercises" ("id")
    INITIALLY DEFERRED;

